更新和修复
zzpong/Interactive-ASM-Cheats-Updater pull request #11
Opened 2024-05-04 06:10 UTC by wzsx150

自动更新金手指工具的代码更新：
1、在对输入的旧金手指数据进行处理分段时，利用两个 \n 分段的形式显然不太合理，应该以 [ 或者 { 进行分段。做了一定的修订，但是没有重构这块的所有代码。优化了代码规范化处理。
2、broadcast_link_update 对一些地址的寻址，代码中存在一些问题，导致无法找到对的地址。
3、支持大师码与普通码之间交叉引用，目前只是支持大师码引用普通码，但普通码不能引用大师码。已完成双向交叉引用功能且大师码可以引用大师码。
4、当金手指向text段地址写入数据时，如果地址是倒着连续的，此时输出的地址则是正着连续的。是由于判断code_chunk是否可以合并时使用了绝对值，不是正值。已修复。
5、优化：UI界面默认使用等宽字体。
6、优化：日志信息区默认不再滑动到最后一行。
7、新增：UI界面显示BID。
8、修复金手指输出区域右键菜单copy的翻译。
9、金手指输入和输出区域增加右键菜单全选，更便利。
10、优化了一些翻译，并修复代码类型识别正则表达式中英文不一致的问题。
11、新增提示小窗口标题的语言映射表，方便中文界面的内容显示的统一。
12、修正保存文件后的提示窗口的翻译。
13、新增补全缺失的0xF0、0xFF0、0xFF1、0xFFF类型代码，增加（自定义）填充字符类型代码的识别（即00000000开头的金手指）。
14、增加了代码规范化处理后的弹窗提示，方便用户了解进行了规范化处理，因为规范化处理可能会清除一些金手指代码。增加了全部处理完成的弹窗提示。
15、修复bug：撤销到最后一步时，恢复到起始状态时，程序多做了一些操作的bug。
16、优化“生成”按钮显示逻辑，初始时改成开始，后续步骤继续使用生成。
17、增加正在处理的提示窗，解决程序运行时界面卡住的情况。
18、增加旧金手指输入区域对正在处理的金手指代码高亮显示。
19、优化金手指代码的识别，支持识别更多地址段。包括 branch_to_multi、branch_multi_offset 也进行了相应的调整修改。
20、优化GUI界面显示部分内容。
21、增加对rodata和rwdata区的代码的识别和处理，显示对应地址数据的Hex值，但是该功能偏弱，可用性不高。
22、增加识别部分0x5类型金手指代码
23、增加18.0.0 的 key 文件
24、修改main文件名为 NSCodeUpdater.py
25、更新 readme 文件，修改生成exe文件命令
26、对main文件即NSO是否压缩的识别算法更加准确，判断是否正常解压NSO的算法更加准确，避免分析压缩的NSO文件。
27、使用python移植nsnsotool工具，并做了一些调整。
新增：安装模块要求lz4模块。
修复main文件路径中包含中文时，无法正常解压缩的bug
调整main文件解压和备份的机制，删除main文件备份的逻辑，改为解压到另外一个文件。
28、添加一些日志输出到日志文件，增强日志文件的作用。
还在继续...

2024-05-04 06:11 UTC, wzsx150 commented
还在继续，大佬先看看现在的修改内容。

2024-05-04 08:26 UTC, zzpong commented
十分感谢你的修正！这工作量一看就吓人~
不过目前我在忙论文的事情，像热锅上的蚂蚁，甚至连具体修正内容都没空看。如果下个月有时间，我可能会连同你所给的修改，结合自己之前想做的东西，再把软件优化下。谢谢~

2024-05-04 09:14 UTC, wzsx150 commented
> 十分感谢你的修正！这工作量一看就吓人~ 不过目前我在忙论文的事情，像热锅上的蚂蚁，甚至连具体修正内容都没空看。如果下个月有时间，我可能会连同你所给的修改，结合自己之前想做的东西，再把软件优化下。谢谢~

不客气，也是因为比较喜欢大佬做的这个工具，所以才投入时间搞的。我自己编程能力有限，连肝了一周多，好多地方肯定写的并不是很好。我还加了一些我自己使用过程中感觉比较实用的改进，不一定都是好点子。
也感谢大佬的工具，方便小白，毕竟去找金手指的人有几个会自己动手做的；也方便金手指开发者，提高效率，节约很多时间。

我后面把我想要修改的内容都提交，然后也会把我发现的没解决的问题贴出来，等大佬有时间了慢慢改进。
希望这个工具能越来越好。

2024-05-04 09:18 UTC, zzpong commented
已经很好啦，修正量把我都震惊到了~ 也祝愿你通过修正这个项目，在未来编程道路上越走越宽~

2024-05-04 16:28 UTC, wzsx150 commented
接上面，后续更新内容有：
29、金手指输入区域自动滚动，改成滚动到高亮+3行的位置。
30、增加更多动作时弹出正在处理小窗提示，精简代码。
31、正在处理窗口加边框。
32、修复sleep调用。
33、优化部分异常报错机制和逻辑关系，增加部分日志记录项。
34、修改日志信息区域输出的日志的时间戳格式、日志文件的时间戳格式，兼顾中英文习惯。

目前发现的未解决的问题：
1、对于写入 code cave 地址的金手指的处理还存在一些问题，比如当旧金手指的cave地址是倒序的或者乱序时，输出结果的地址肯定会有问题（输出结果只会地址递增）；再比如多个标题里的旧金手指写入相同的cave地址的情况。
2、保存nso文件功能，实际保存后的文件没有被修改，和新金手指main文件一样（main文件可能需要在解压状态下对比）。
3、对于rodata和rwdata段的数据匹配和搜索的思路，目前只是按各自段偏移进行输出结果地址，没有对地址内容进行搜索和匹配，不知道大佬有没有什么好的思路。对金手指接触不多，不清楚这种情况的金手指有没有？
4、加载nsz模块的时机能不能进行延后？这样可以防止缺少 key.txt 和 prod.keys 文件导致的程序崩溃，因为大部分情况下不需要使用nsz解包。打包好的exe文件，一运行就会加载nsz，然后就会检测key.txt。不过不影响使用，不改动也没问题。
5、加载游戏文件、解压游戏文件时，弹窗显示正在处理，我的方案比较简单粗暴，不确定存不存在潜在bug。

目前就这样了，我也还没有进行严格的测试，我最近会继续实际用用新版，如果发现新的bug，我也会继续提交。
另外如果有机会，我也会在论坛推广推广（虽然人微言轻）。

2024-05-09 09:57 UTC, wzsx150 commented
35、调整图标生成的路径，不再删除目录内图标文件，避免出现找不到"xcw.ico"的情况。
36、确保强制退出按钮能够退出所有线程。
37、修改点击开始按钮后弹窗的时机。
38、加载一次文件后，然后又不加载文件时，界面上BID的显示优化。
39、增加支持cbz、cbnz、tbz、tbnz类型的跳转。
40、调整上一个、下一个按钮的可用逻辑。

2024-05-11 10:39 UTC, wzsx150 commented
41、当新版main中匹配不到地址时，仅显示旧版main对应地址的ASM。
42、修复上一个、下一个按钮的作用。
43、减少程序运行过程中的内存占用。
44、优化正在处理窗口的显示。
45、测试：重构asm代码查找算法，使用bit字节串进行查找匹配，提高匹配准确性。

目前发现的未解决的问题：
6、无法定位的一个报错，但并不影响程序的正常运行：
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
TypeError: <lambda>() missing 1 required positional argument: 'event'

截止到目前，我应该基本上把我需要修复和修改的内容都提交了，后面就交给大佬了。

2024-06-27 04:45 UTC, zzpong approved these changes

2024-06-27 04:53 UTC, zzpong requested changes
感谢您的建议~ 原代码并非简单使用两“\n”进行分段，金手指中即使没有“\n”依旧可以正确分段。相反，如果使用“[”或“{”进行分段，则会将多个连续标题拆分成不同段落（如：[标题][作者信息][第一条金手指] 第一条金手指内容），因此这儿并不进行修正。

2024-06-27 05:00 UTC, zzpong commented
感谢您的一系列修正内容使本项目变得更加完善得体。
但由于修正项目过多，且并不一定适用当前应用场景，因此这儿仅对每处修正位置进行详细回复。
之后会在上述内容修正完成、且追加我这额外想要更新内容后，上传包含您致谢信息的版本。
再次感谢您的建议~

2024-06-27 06:18 UTC, zzpong approved these changes
感谢纠正~ 这么细节的问题都发现了！其实上文已经有cur_position2变量（名叫offset），只不过后来写顺手忘了改 -。-

2024-06-27 06:48 UTC, zzpong approved these changes
不错的建议，确实只要不是普通码跳转另一个普通码，都算合理金手指。

2024-06-27 07:14 UTC, zzpong approved these changes
之前想要兼容反向连续地址金手指代码才这么写的，现在看确实欠考虑。想要实现这个功能不能仅使用abs()，还需要在代码很多地方增加reverse信息。由于增加这部分功能输出结果类似、时间仅少量减少、引入额外bug、且代码更新代价过大，因此直接采纳此处修改方法，不进一步更新功能。

2024-06-27 07:19 UTC, zzpong requested changes
感谢建议。移除此行代码后并未见明显变化，可能不同电脑导致，目前美化问题暂时搁置。

2024-06-27 07:24 UTC, zzpong approved these changes
很不错的建议，感谢~

2024-06-27 07:34 UTC, zzpong approved these changes
感谢建议~ 很不错的想法，可以让所提供信息更加清晰。

2024-06-27 07:36 UTC, zzpong approved these changes
多谢建议，内容已修正

2024-06-27 07:40 UTC, zzpong approved these changes
不错的建议，已修正

2024-06-27 08:24 UTC, zzpong approved these changes
感谢这么详细的修正建议。code_0x0本身在预处理过程中已被切分为最长为2的代码（考虑到不切分会导致后续处理极度复杂），4/8长度并不生效，因此未做修改。其余部分均已参考修改内容对代码进行完善~

2024-06-27 08:28 UTC, zzpong requested changes
感谢建议及详细修正。但提示信息这部分词汇已接近OK、Cancel之类的通用性，且每个提示框都包含额外显眼警告与错误标志，因此并未进行修正。

2024-06-27 08:40 UTC, zzpong approved these changes
感谢建议，已修正~

2024-06-27 09:31 UTC, zzpong approved these changes
感谢建议，这部分功能已添加~

2024-06-27 09:32 UTC, zzpong requested changes
感谢建议。但弹窗会进一步增加用户操作量，并已经有不少用户反应想要一键生成功能，因此该功能有待考量。

2024-06-27 09:34 UTC, zzpong approved these changes
感谢建议，已修复。

2024-06-27 09:37 UTC, zzpong approved these changes
很不错的建议，并且所有该修改的地方都改掉了，多谢啦~

2024-06-27 09:40 UTC, zzpong requested changes
感谢建议，这个想法很不错。提出的原因应该是为解决定位地址时可能等待时间过长甚至假死问题。但如果能够将查找定位地址作为协程独立出来，也可以很好的避免这个问题，这也是本项目未来更新目标之一。

2024-06-27 11:06 UTC, zzpong approved these changes
确实是个好建议~ 已按类似思路提示用户当前正在处理代码位置。

2024-06-27 11:13 UTC, zzpong requested changes
金手指代码通常不会写入只读、可读写以及变量bss区域，随意修改这部分内容有极大概率使游戏在特定位置因数据损坏而导致黑屏。因此这部分更新需要在未来慎重考虑后再做决定，但依然感谢您的宝贵建议与代码修正内容~

2024-06-27 11:16 UTC, zzpong requested changes
感谢您在UI方面的修正，这部分修正可能在大更新版本更新时考虑加进去，目前暂时不打算修改。

2024-06-27 11:18 UTC, zzpong requested changes
能够Hex显示确实是个好点子，但同之前说过的一样，目前没有增加rodata和rwdata这些危险区域修改的打算，且当前UI也不适合显示Hex内容。因此可能在未来大版本更新时考虑增加这部分内容。再次感谢您的修改建议~

2024-06-27 11:29 UTC, zzpong approved these changes
在本工具出现大概一年后，0x5类型的金手指开始逐步出现。实际上0x5相当于把0x0代码进行复杂化包装，以防止其他用户直接使用本工具进行更新。由于过于错综复杂关系，比如更新金手指后说是自己的、甚至嘲讽作者等等事情，目前此功能是否更新还处在模糊阶段，权当金手指作者不愿意其他人代替更新金手指的自由选择。具体是否要实现此功能、如何实现此功能并保证所有结果完全正确，还需等待一段时间。另外，这种功能通常仅在国内金手指中出现，国外反馈并不强烈。

2024-06-27 11:30 UTC, zzpong approved these changes
感谢更新~

2024-06-27 11:31 UTC, zzpong approved these changes
没啥问题，萝卜白菜各有所爱~

2024-06-27 11:35 UTC, zzpong requested changes
合并dll确实能让软件简洁，但保留这些dll更多是出于版权问题。在未授权情况下通常是无权整合dll文件并不加以标识的，nsnsotool也是同样道理。依旧感谢您的建议~

2024-06-27 11:56 UTC, zzpong requested changes
感谢建议，原代码def decompress(self)函数的except Exception部分已有检测。

2024-06-27 11:59 UTC, zzpong requested changes
感谢建议。在未经nsnsotool作者允许情况下，通常不对其他软件进行直接整合；备份main是为避免用户误操作导致的文件丢失问题，直接备份源文件也可以方便用户直接拷贝。

2024-06-27 12:00 UTC, zzpong approved these changes
感谢建议，确实增加了不错的log信息~

2024-06-27 12:04 UTC, zzpong requested changes
感谢建议~ 但由于之前高亮内容未采用完全相同展示方式，因此这儿无需更新。

2024-06-27 12:05 UTC, zzpong requested changes
感谢建议。但这儿不推荐增加窗口，会增加用户不停点击关闭窗口而产生的厌烦度。

2024-06-27 12:07 UTC, zzpong requested changes
由于未采用额外“小窗口”提醒，因此这儿也不进行修正。

2024-06-27 12:08 UTC, zzpong requested changes
由于未采用额外“小窗口”提醒，因此这儿也不进行修正。

2024-06-27 12:11 UTC, zzpong approved these changes
感谢您对log部分的优化，这部分将在未来版本更新~

2024-06-27 12:12 UTC, zzpong approved these changes
感谢您对时间格式的建议~

2024-06-27 12:22 UTC, zzpong requested changes
为避免打包成应用时资源图标独立显示，本工具将xcw.ico提前写入base64一并打包；随后在生成所需xcw资源后再对缓存图进行移除。这里的修正内容挺不错，完美解决python调试时找不到xcw.ico的情况，但丧失了上面所说应用程序的功能。

2024-06-27 12:23 UTC, zzpong requested changes
该PR对应的基础PR并未采用，因此并未更新。

2024-06-27 12:24 UTC, zzpong requested changes
该PR对应的基础PR并未采用，因此并未更新。

2024-06-27 12:25 UTC, zzpong approved these changes
感谢建议，已更新~

2024-06-27 12:53 UTC, zzpong approved these changes
感谢新增功能，已追加~

2024-06-27 12:53 UTC, zzpong requested changes
感谢建议，感觉只是思路不同~

2024-06-27 12:58 UTC, zzpong requested changes
感觉也是观念不同，两者都可行。

2024-06-27 12:59 UTC, zzpong requested changes
该PR对应的基础PR并未采用，因此并未更新。

2024-06-27 13:04 UTC, zzpong requested changes
该PR对应的基础PR并未采用，因此并未更新。

2024-06-27 13:05 UTC, zzpong requested changes
该PR对应的基础PR并未采用，因此并未更新。

2024-06-27 13:07 UTC, zzpong requested changes
main文件的指令均为字节对齐、甚至还有padding专门负责对齐，无需bit定位。即使bit定位到，也不满足main文件要求，只是巧合罢了。

2024-06-27 13:09 UTC, zzpong commented
> 41、当新版main中匹配不到地址时，仅显示旧版main对应地址的ASM。 42、修复上一个、下一个按钮的作用。 43、减少程序运行过程中的内存占用。 44、优化正在处理窗口的显示。 45、测试：重构asm代码查找算法，使用bit字节串进行查找匹配，提高匹配准确性。
> 
> 目前发现的未解决的问题： 6、无法定位的一个报错，但并不影响程序的正常运行： Exception in Tkinter callback Traceback (most recent call last): File "D:\Python\Python39\lib\tkinter__init__.py", line 1892, in **call** return self.func(*args) TypeError: () missing 1 required positional argument: 'event'
> 
> 截止到目前，我应该基本上把我需要修复和修改的内容都提交了，后面就交给大佬了。

此项bug可能是引入process导致的，由于项目暂未采用这种额外弹窗功能，因此并未继续研究处理。

2024-06-27 13:54 UTC, merged